name: Editor tests
on:
  pull_request:
  push:
    branches: ['master']
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ATOM_JASMINE_REPORTER: list

jobs:
  tests:
    name: Tests
    if: |
      !startsWith(github.event.pull_request.title, '[skip-ci]') &&
      !startsWith(github.event.pull_request.title, '[skip-editor-ci]')
    strategy:
      matrix:
        # os: [ubuntu-20.04, macos-latest, windows-2019]
        os: [ubuntu-20.04, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Python setuptools
      # This is needed for Python 3.12+, since many versions of node-gyp
      # are incompatible with Python 3.12+, which no-longer ships 'distutils'
      # out of the box. 'setuptools' package provides 'distutils'.
      run: python3 -m pip install setuptools

    - name: Install Dependencies
      run: yarn install --ignore-engines || yarn install --ignore-engines

    - name: Build Dependencies
      run: yarn build

    - name: Run Tests
      uses: coactions/setup-xvfb@v1.0.1
      with:
        run: node script/run-tests.js spec
